Refactor messages regarding chat
PTS3-S34A/Game-Server pull request #23
Opened 2016-12-21 13:22 UTC by BeeHiveJava

2016-12-21 13:23 UTC, TehMessiah commented on Soccar [Game-Server]/src/nl/soccar/gameserver/model/command/CommandListener.java
> +    public abstract void execute(PlayerWrapper player, Chat chat, Command command);
![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png) Document this public method. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](http://194.135.91.67:9000/coding_rules#rule_key=squid%3AUndocumentedApi)

2016-12-21 13:23 UTC, ghost commented on Soccar [Game-Server]/src/nl/soccar/gameserver/model/command/CommandListener.java
>      public final void executePrivileged(PlayerWrapper player, Command command) {
![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png) Document this public method. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](http://194.135.91.67:9000/coding_rules#rule_key=squid%3AUndocumentedApi)

2016-12-21 13:23 UTC, TehMessiah commented on Soccar [Game-Server]/src/nl/soccar/gameserver/model/Chat.java
> +    public void mutePlayer(PlayerWrapper issuer, String username) {
![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png) Document this public method. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](http://194.135.91.67:9000/coding_rules#rule_key=squid%3AUndocumentedApi)

2016-12-21 13:23 UTC, TehMessiah commented on Soccar [Game-Server]/src/nl/soccar/gameserver/model/Chat.java
> +    public void unmutePlayer(PlayerWrapper issuer, String username) {
![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png) Document this public method. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](http://194.135.91.67:9000/coding_rules#rule_key=squid%3AUndocumentedApi)

2016-12-21 13:23 UTC, TehMessiah commented on Soccar [Game-Server]/src/nl/soccar/gameserver/model/Chat.java
> +    public Chat(RoomWrapper room) {
![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png) Document this public constructor. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](http://194.135.91.67:9000/coding_rules#rule_key=squid%3AUndocumentedApi)

2016-12-21 13:23 UTC, TehMessiah commented on Soccar [Game-Server]/src/nl/soccar/gameserver/model/Chat.java
> +    public void sendChatMessage(PlayerWrapper player, String message) {
![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png) Document this public method. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](http://194.135.91.67:9000/coding_rules#rule_key=squid%3AUndocumentedApi)

2016-12-21 13:23 UTC, TehMessiah commented on Soccar [Game-Server]/src/nl/soccar/gameserver/model/session/RoomWrapper.java
>      public RoomWrapper(SessionWrapper session, Room room) {
![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png) Document this public constructor. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](http://194.135.91.67:9000/coding_rules#rule_key=squid%3AUndocumentedApi)

2016-12-21 13:23 UTC, TehMessiah commented on Soccar [Game-Server]/src/nl/soccar/gameserver/model/session/RoomWrapper.java
>      public void join(PlayerWrapper player, String password) {
![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png) Document this public method. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](http://194.135.91.67:9000/coding_rules#rule_key=squid%3AUndocumentedApi)

2016-12-21 13:23 UTC, TehMessiah commented
SonarQube analysis reported 15 issues
* ![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png) 15 minor

Watch the comments in this conversation to review them.

#### 7 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png) [CommandListener.java#L18](https://github.com/PTS3-S34A/Game-Server/blob/dde0d5a179ebe8082d9a1d312b5d23274b844a05/Soccar [Game-Server]/src/nl/soccar/gameserver/model/command/CommandListener.java#L18): Document this public constructor. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](http://194.135.91.67:9000/coding_rules#rule_key=squid%3AUndocumentedApi)
1. ![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png) [CommandListener.java#L22](https://github.com/PTS3-S34A/Game-Server/blob/dde0d5a179ebe8082d9a1d312b5d23274b844a05/Soccar [Game-Server]/src/nl/soccar/gameserver/model/command/CommandListener.java#L22): Document this public constructor. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](http://194.135.91.67:9000/coding_rules#rule_key=squid%3AUndocumentedApi)
1. ![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png) [BroadcastCommandListener.java#L15](https://github.com/PTS3-S34A/Game-Server/blob/dde0d5a179ebe8082d9a1d312b5d23274b844a05/Soccar [Game-Server]/src/nl/soccar/gameserver/model/command/listener/BroadcastCommandListener.java#L15): Document this public constructor. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](http://194.135.91.67:9000/coding_rules#rule_key=squid%3AUndocumentedApi)
1. ![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png) [MuteCommandListener.java#L14](https://github.com/PTS3-S34A/Game-Server/blob/dde0d5a179ebe8082d9a1d312b5d23274b844a05/Soccar [Game-Server]/src/nl/soccar/gameserver/model/command/listener/MuteCommandListener.java#L14): Document this public constructor. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](http://194.135.91.67:9000/coding_rules#rule_key=squid%3AUndocumentedApi)
1. ![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png) [UnmuteCommandListener.java#L14](https://github.com/PTS3-S34A/Game-Server/blob/dde0d5a179ebe8082d9a1d312b5d23274b844a05/Soccar [Game-Server]/src/nl/soccar/gameserver/model/command/listener/UnmuteCommandListener.java#L14): Document this public constructor. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](http://194.135.91.67:9000/coding_rules#rule_key=squid%3AUndocumentedApi)
1. ![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png) [RoomWrapper.java#L82](https://github.com/PTS3-S34A/Game-Server/blob/dde0d5a179ebe8082d9a1d312b5d23274b844a05/Soccar [Game-Server]/src/nl/soccar/gameserver/model/session/RoomWrapper.java#L82): Document this public method. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](http://194.135.91.67:9000/coding_rules#rule_key=squid%3AUndocumentedApi)
1. ![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png) [RoomWrapper.java#L116](https://github.com/PTS3-S34A/Game-Server/blob/dde0d5a179ebe8082d9a1d312b5d23274b844a05/Soccar [Game-Server]/src/nl/soccar/gameserver/model/session/RoomWrapper.java#L116): Document this public method. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](http://194.135.91.67:9000/coding_rules#rule_key=squid%3AUndocumentedApi)

2016-12-22 20:49 UTC, Ranray requested changes

2016-12-22 20:49 UTC, Ranray commented on Soccar [Game-Server]/src/nl/soccar/gameserver/model/Chat.java
> +            player.getConnection().send(new ChatMessage(-1, Privilege.ADMINISTRATOR, "You have been muted and, therefor, cannot talk."));
Graag een constante toevoegen voor de -1 waarde in de ChatMessage.

2016-12-22 20:49 UTC, Ranray commented on Soccar [Game-Server]/src/nl/soccar/gameserver/model/Chat.java
> +        optional.get().getConnection().send(new ChatMessage(-1, Privilege.ADMINISTRATOR, "You have been muted."));
Graag een constante toevoegen voor de -1 waarde in de ChatMessage.

2016-12-22 20:49 UTC, Ranray commented on Soccar [Game-Server]/src/nl/soccar/gameserver/model/Chat.java
> +        optional.get().getConnection().send(new ChatMessage(-1, Privilege.ADMINISTRATOR, "You have been unmuted."));
Graag een constante toevoegen voor de -1 waarde in de ChatMessage.

2016-12-22 20:49 UTC, Ranray commented on Soccar [Game-Server]/src/nl/soccar/gameserver/model/Chat.java
> +        issuer.getConnection().send(new ChatMessage(-1, Privilege.ADMINISTRATOR, String.format("You have unmuted %s.", username)));
Graag een constante toevoegen voor de -1 waarde in de ChatMessage.

2017-01-09 11:23 UTC, BeeHiveJava commented
Won't implement, not really necessary. Plus I'm not too proud of the format.

2017-01-09 11:23 UTC, closed without merging